server:
port: 8080

spring:
  application:
    name: accounts-service

  datasource:
    url: jdbc:postgresql://localhost:5432/colleger-accountsdb
    username: jordan
    password: 42069
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Optional: to display SQL queries in the console
