apiVersion: v1
kind: Service
metadata:
  name: colleger-student-microservice-service
spec:
  type: NodePort
  selector:
    app: colleger-student-microservice
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30004
