apiVersion: apps/v1
kind: Deployment
metadata:
  name: colleger-frontend-deployment
spec:
  selector:
    matchLabels:
      app: colleger-frontend
  template:
    metadata:
      labels:
        app: colleger-frontend
    spec:
      containers:
      - name: colleger-frontend-microservice
        image: thevikashpratapsingh/colleger-frontend:latest
        imagePullPolicy: Always
        resources:
          requests: 
            memory: "128Mi"
            cpu: "250m"  
          limits:
            memory: "256Mi"
            cpu: "400m"
        ports:
        - containerPort: 80
        
        
