name: sample_workflow
on: workflow_dispatch
jobs:
  first_job:
   runs-on: ubuntu-latest
   steps:
     - name: greet-the-user
       run: echo "Hello User"
     - name: bye-bye-the-use
       run: echo "Bye Bye ${{ github.actor }}"